# Generated by Django 2.1.5 on 2019-06-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(related_name='orders', through='foodDelivery.OrderFoodItem', to='foodDelivery.FoodItem'),
        ),
        migrations.AddField(
            model_name='orderfooditem',
            name='food_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodDelivery.FoodItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfooditem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodDelivery.Order'),
            preserve_default=False,
        ),
    ]
